version: '3.9'

services:

  redis:
    image: redis:7.2.3-alpine
    ports:
      - '6380:6379'

  db:
    image: postgres:16.2-alpine3.19
    env_file:
      - .env.docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      django-admin compilemessages &&
      python manage.py load_fixtures &&
      python manage.py fill_cars &&
      python manage.py csu &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./.env.docker:/code/.env

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - db
      - redis
      - app
    volumes:
      - ./.env.docker:/code/.env

  celery_beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - db
      - app
      - celery
    volumes:
      - ./.env.docker:/code/.env

volumes:
  pg_data: